### ISSUE TITLE
mcob: seq192: conflit entre couplet1-2_samples_princeguitar  et couplet1-2_samples_princeguitar2

### ISSUE THREAD

**Issue by jean-emmanuel** [PlagiatBros/PlagiatSetupII#10]

**Comment by orlammd** [comment]
tu parles des séquences dans seq192 ? Elles y étaient toutes les deux dans le truc d'origine. C'est pas exactement le même traitement, et je sais pas pourquoi on avait fait ça, mais j'ai décidé de ne pas toucher particulièrement à ce qui semblait marcher.
