### ISSUE TITLE
Regler les gate (vx=

### ISSUE THREAD

**Issue by jean-emmanuel** [PlagiatBros/PlagiatSetupII#19]

**Comment by orlammd** [comment]
Gate pré-réglés + routing revu + compresseur / eq pré-réglé.
Compression NY ?
Compression MID-Side (je ne vois pas trop comment) ?

**Comment by jean-emmanuel** [comment]
Le mid-side est plus pertinent en mastering si j'ai bien compris. En fait ma remarque sur ces traitement ne portait pas spécifiquement sur les voix, j'avais pas précisé..

**Comment by orlammd** [comment]
Yep, le NY peut se faire sur les voix, cela dit (et pas forcément à très 
cher). Je ferai des essais si j'ai le temps Vendredi.

Le 09/05/2022 à 19:51, jean-emmanuel a écrit :
