### ISSUE TITLE
regler tonalités des morceaux

### ISSUE THREAD

**Issue by jean-emmanuel** [PlagiatBros/PlagiatSetupII#22]
via autotune.set_scale()

**Comment by orlammd** [comment]
normalement ok, j'ai dû créer un module Notes pour pas avoir à expliciter les autotuners à chaque fois via une boucle.

**Comment by jean-emmanuel** [comment]
Ok, ce serait plus pertinent de l'appeler tonality ? et peut-être de le fusionner avec microtonality. Le fichier du module n'est pas suivi dans git.

**Comment by orlammd** [comment]
OK, je le giterai demain.
J'avais pensé à le mettre dans microtonality, mais je voulais pas 
pourrir ton code.

A la réflexion, on devrait appeler microtonality "Makham" ou "Mode" et 
mettre dedans des dictionnaires de notes + microtonalités qu'on pourrait 
appeler, et éventuellement altérer en faisant un + d# ou ce genre de 
choses ?
Ca permettrait de ne pas toujours utiliser le même makham (ce que je 
souhaiterais à titre perso), et d'être un peu moins sale (tout en le 
restant).
A l'occaz, je veux bien m'occuper de ça quand on mettra les nouveaux 
morceaux en place (dans l'attente, ça fonctionne comme ça, je pense).

Le 09/05/2022 à 19:47, jean-emmanuel a écrit :
