### ISSUE TITLE
keyboard: trop de sons de synthés pour la gui

### ISSUE THREAD

**Issue by jean-emmanuel** [PlagiatBros/PlagiatSetupII#25]
Il y a trop de sons de synthé pour tout mettre dans la gui sans que ça devienne fastidieux de choisir le son (soit les boutons sont petits, soit il faut passer par un menu qui demande un clic de plus). @orlammd est-ce qu'il y a des sons dans Mididings/keyboard.py que tu ne joues jamais avec le clavier ?

**Comment by jean-emmanuel** [comment]
En l'état voilà ce qui me semble le plus lisible, avec une fenêtre modale:
![Capture d’écran_2022-05-07_17-58-11](https://user-images.githubusercontent.com/5261671/167262239-f83e8778-c744-4eac-8096-bbc111b30bd1.png)

**Comment by orlammd** [comment]
Le 07/05/2022 à 17:59, jean-emmanuel a écrit :
> En l'état voilà ce qui me semble le plus lisible, avec une fenêtre modale:
> Capture d’écran_2022-05-07_17-58-11 
> <https://user-images.githubusercontent.com/5261671/167262239-f83e8778-c744-4eac-8096-bbc111b30bd1.png>

Je pense que ça peut le faire, surtout si on peut faire apparaître la 
modale via mentat, et que c'est déjà prêt pour le clic unique, du coup.

**Comment by jean-emmanuel** [comment]
Ok. Je pense que si on en est à montrer la modale via mentat, autant choisir le son direct depuis mentat non ?

**Comment by orlammd** [comment]
Il peut y avoir des besoins de changer de sons a la mano (et sans savoir 
à l'avance), sur certains passages (SW drum'n'bass), mais bon, avec deux 
clic ça gère aussi.

Le 07/05/2022 à 23:00, jean-emmanuel a écrit :

**Comment by jean-emmanuel** [comment]
yes les deux options restent à disposition de toute façon

Le 08/05/2022 à 11:08, ORL - AMMD a écrit :
