### ISSUE TITLE
Autotuner crash quand gros signal

### ISSUE THREAD

**Issue by orlammd** [PlagiatBros/PlagiatSetupII#27]
Est-ce qu'on aurait repris une version qui ne résoud plus ce pb ?

**Comment by jean-emmanuel** [comment]
chelou, je vais regarder ça

**Comment by jean-emmanuel** [comment]
Le correctif que j'avais fait pour ce problème date de bien avant d'autres ajouts qu'on a (genre fast mode) donc ça me parait pas possible. Je n'arrive pas à le faire tomber chez moi cela dit.

**Comment by orlammd** [comment]
brancher le micro suffit à faire tomber (de ce que j'ai pu en remarquer)

**Comment by orlammd** [comment]
corrigé
