### ISSUE TITLE
Mentat restore les valeurs des sous-modules y compris en période de dev

### ISSUE THREAD

**Issue by orlammd** [PlagiatBros/PlagiatSetupII#28]
Pas vraiment un bug, plutôt une réflexion.
Lorsque je modifie des choses (par exemple un gate dans non-mixer), et que je lance un bouton dans mentat (ou changement de morceau, j'ai pas bien identifié), mentat renvoie les valeurs "par défaut". Pb : si je viens de régler un plug et que, genre, je veux écouter le résultat, il écrase le réglage.
Je ne sais pas trop ce qu'on pourrait faire (à part être prudent). Peut-être un message à envoyer à mentat pour le mettre "hors d'état de nuire" ponctuellement ? Je ne sais pas...

**Comment by jean-emmanuel** [comment]
Oui c'est un des trucs que j'avais laissé en suspend, je vais voir mercredi pour faire un mode "dev".

**Comment by jean-emmanuel** [comment]
Le seul truc que je vois qui s'approche de ce que tu décris, c'est en cas de redémarrage d'un client raysession pendant que mentat tourne: à ce moment là mentat est censé renvoyer les valeurs initiale, mais ça ne fonctionnait pas je viens de le corriger (et on peut court-circuiter ça en mettant --dev au lancement de mentat)
