### ISSUE TITLE
pb avec OSC et Sooperlooper (pb sync)

### ISSUE THREAD

**Issue by orlammd** [PlagiatBros/PlagiatSetupII#30]
Yo !
J'ai pas encore compris comment ni pourquoi, mais le comportement de sooperlooper contrôlé par OSC est chelou.
Si tu appuies sur record, il se met en wait (dans osc), puis finit par passer en record (mais visiblement pas dans sooperlooper).
ENsuite, quoi qu'il en soit, au bout d'un moment, il stoppe le record (testé sur couplet Snapshat), mais on entend rien. Si je relance le bouton 3 (qui a un play), alors la boucle enregistrée sort finalement...

**Comment by orlammd** [comment]
pour préciser, c'est sooperlooper qui semble arrêter l'enregistrement de lui-même (enregistrement long), et même pas en fin de mesure

**Comment by jean-emmanuel** [comment]
chelou, j'avais déjà testé tout ça sans souci, je regarde ça dimanche

Le 13/05/2022 à 09:22, ORL - AMMD a écrit :
