### ISSUE TITLE
Surmonitors Synths pour Missy

### ISSUE THREAD

**Issue by orlammd** [PlagiatBros/PlagiatSetupII#40]

**Comment by orlammd** [comment]
Done - si tu veux jeter un oeil. Ca a l'air de fonctionner, mais c'est assez sale (ça n'évite pas les synthés basse dans la liste, alors que ça ne peut pas agir dessus, par exemple)

**Comment by orlammd** [comment]
Accessoirement, est-ce que ça serait possible d'avoir un bouton "boost" dans l'interface qui, s'il est actif, envoie set_sound('le_son', jmjBoost=True) quand je sélectionne un son ?

**Comment by jean-emmanuel** [comment]
J'ai bougé ton code vers une methode dédiée 'set_boost()', et viré la partie mk2, de toute façon il y a un module keyboard pour toi et pour moi donc au besoin on pourra gerer le boost séparément, du coup l'option 'jmjBoost' devient simplement 'boost'. petit détail, j'utilise le snake case partout ailleur dans le code pour les noms de variables (il aurait donc fallu écrire 'jmj_boost')

**Comment by jean-emmanuel** [comment]
je me rends compte qu'on est en camel case sur les noms des variables qui pointent vers nos modules, pas facile la cohérence ! disons que c'est l'exception qui..
